{
  "hash": "371955517a4c3a41610e006528b9d18c",
  "result": {
    "markdown": "---\ntitle: \"blog post 7\"\nauthor: \"team 2\"\ndate: \"2023-12-11\"\ndate-modified: \"2023-12-11\"\n\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"caret\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: ggplot2\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nLoading required package: lattice\n```\n:::\n\n```{.r .cell-code}\nlibrary(\"corrplot\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\ncorrplot 0.92 loaded\n```\n:::\n\n```{.r .cell-code}\nlibrary(\"tidyverse\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.3     ✔ readr     2.1.4\n✔ forcats   1.0.0     ✔ stringr   1.5.0\n✔ lubridate 1.9.3     ✔ tibble    3.2.1\n✔ purrr     1.0.2     ✔ tidyr     1.3.0\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n✖ purrr::lift()   masks caret::lift()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\nbirth_sample<-read.csv(\"cleanedbirth.csv\")\nBirthStat <- read.csv(\"dataset/BirthStat.csv\")\nYI <- read.csv(\"dataset/Yearly income data.csv\")\nbirthdata <-read.csv(\"dataset/cleanedbirth.csv\")\ncombirth <- birthdata |>\n  left_join(BirthStat, by = c(\"Year\" = \"Year\"))\ncombirth <- combirth |>\n  left_join(YI, by = c(\"Year\" = \"Year\"))\nbirthweightmodel <- lm(dbwt ~ mager+ meduc+ m_ht_in+  bmi+ pwgt_r+ dwgt_r+  Married+ GDiabetes+ cig_before+ cig_during, data=birth_sample)\nsummary(birthweightmodel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = dbwt ~ mager + meduc + m_ht_in + bmi + pwgt_r + \n    dwgt_r + Married + GDiabetes + cig_before + cig_during, data = birth_sample)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3347.0  -289.1    35.3   347.1  7253.0 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 2130.88988   31.53166  67.579  < 2e-16 ***\nmager         -4.84537    0.39108 -12.390  < 2e-16 ***\nmeduc          8.92433    1.30215   6.854 7.24e-12 ***\nm_ht_in       17.59571    0.49910  35.255  < 2e-16 ***\nbmi           -3.55587    0.36027  -9.870  < 2e-16 ***\npwgt_r         0.19442    0.03625   5.363 8.22e-08 ***\ndwgt_r         0.39368    0.01918  20.523  < 2e-16 ***\nMarried       86.43417    4.22763  20.445  < 2e-16 ***\nGDiabetes     -5.43742    7.37829  -0.737    0.461    \ncig_before    67.20483   11.59933   5.794 6.90e-09 ***\ncig_during  -259.91138    8.08793 -32.136  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 596.4 on 119989 degrees of freedom\nMultiple R-squared:  0.03344,\tAdjusted R-squared:  0.03336 \nF-statistic: 415.1 on 10 and 119989 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\ncorrelation_matrix <- \n  birth_sample|>\n  select(-Race)|>\n  cor()\ncorrplot(correlation_matrix, method = \"circle\", type = \"upper\", tl.col = \"black\", tl.srt = 45)\n```\n\n::: {.cell-output-display}\n![](blog-post-7_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\npanel.cor <- function(x, y, digits = 2, prefix = \"\", cex.cor, ...) {\n  usr <- par(\"usr\")\n  on.exit(par(usr))\n  par(usr = c(0, 1, 0, 1))}\n  \n  \nmotheragemodel <- lm(mager ~ Year+meduc + m_ht_in + bmi + pwgt_r + dwgt_r + Married + GDiabetes + cig_before + cig_during+Year, data = birth_sample)\noriginal_AIC <- AIC(motheragemodel)\ncommotheragemodel<- lm(mager ~ Year+meduc + m_ht_in + bmi + pwgt_r + dwgt_r + Married + GDiabetes + cig_before + cig_during+Year, data = combirth)\nAIC(motheragemodel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 696234.4\n```\n:::\n\n```{.r .cell-code}\nmotheragemodel <- lm(mager ~ Year+meduc+ m_ht_in+  bmi+ pwgt_r+ dwgt_r+  Married+ GDiabetes+ cig_before+ cig_during, data=birth_sample)\nsummary(motheragemodel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mager ~ Year + meduc + m_ht_in + bmi + pwgt_r + \n    dwgt_r + Married + GDiabetes + cig_before + cig_during, data = birth_sample)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-19.8342  -3.1093  -0.7844   2.3355  27.8346 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -1.006e+02  1.505e+01  -6.685 2.31e-11 ***\nYear         5.761e-02  7.454e-03   7.729 1.09e-14 ***\nmeduc        1.565e+00  8.482e-03 184.520  < 2e-16 ***\nm_ht_in      1.698e-02  3.683e-03   4.611 4.02e-06 ***\nbmi          2.834e-02  2.659e-03  10.660  < 2e-16 ***\npwgt_r      -1.884e-03  2.676e-04  -7.039 1.95e-12 ***\ndwgt_r       1.322e-03  1.415e-04   9.345  < 2e-16 ***\nMarried      2.844e+00  3.011e-02  94.477  < 2e-16 ***\nGDiabetes    1.505e+00  5.430e-02  27.714  < 2e-16 ***\ncig_before   2.830e-01  8.564e-02   3.304 0.000952 ***\ncig_during   7.578e-01  5.966e-02  12.701  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.402 on 119989 degrees of freedom\nMultiple R-squared:  0.4179,\tAdjusted R-squared:  0.4178 \nF-statistic:  8614 on 10 and 119989 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAIC(motheragemodel)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 696234.4\n```\n:::\n\n```{.r .cell-code}\ncombirth$underage <- ifelse(birth_sample$mager < 18, 0, 1)\nlogistic_model1 <- glm(underage ~ Year+Number.of.births+Birth.rate.per.1.000.population.+Fertility.rate.births.per.1.000.women.aged.15.44. +Percent.born.low.birthweight+Percent.born.preterm+ Percent.unmarried+Mean.age.at.first.birth+PCI+meduc + m_ht_in + bmi + pwgt_r + dwgt_r + Married + GDiabetes + cig_before + cig_during, family = binomial(), data = combirth)\nlogistic_model2 <- glm(underage ~ Year+PCI+meduc + m_ht_in + bmi + pwgt_r + dwgt_r + Married + GDiabetes + cig_before + cig_during, \n                      family = binomial(), \n                      data = combirth)\n\nlogistic_model3 <- glm(underage ~ Year+meduc + m_ht_in + bmi + pwgt_r + dwgt_r + Married + GDiabetes + cig_before + cig_during, \n                      family = binomial(), \n                      data = combirth)\nAIC(logistic_model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18959.16\n```\n:::\n\n```{.r .cell-code}\nAIC(logistic_model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 18953.39\n```\n:::\n\n```{.r .cell-code}\nAIC(logistic_model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 22206.89\n```\n:::\n\n```{.r .cell-code}\nsummary(logistic_model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = underage ~ Year + meduc + m_ht_in + bmi + pwgt_r + \n    dwgt_r + Married + GDiabetes + cig_before + cig_during, family = binomial(), \n    data = combirth)\n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.140e+02  2.104e+01  -5.417 6.06e-08 ***\nYear         5.525e-02  1.042e-02   5.300 1.16e-07 ***\nmeduc        1.784e+00  2.549e-02  69.980  < 2e-16 ***\nm_ht_in     -1.644e-02  5.659e-03  -2.905  0.00367 ** \nbmi          4.782e-02  5.233e-03   9.137  < 2e-16 ***\npwgt_r      -4.134e-03  5.000e-04  -8.269  < 2e-16 ***\ndwgt_r       1.453e-03  2.560e-04   5.674 1.39e-08 ***\nMarried      3.336e+00  1.116e-01  29.890  < 2e-16 ***\nGDiabetes    9.403e-01  1.289e-01   7.296 2.97e-13 ***\ncig_before   6.958e-01  1.204e-01   5.777 7.60e-09 ***\ncig_during   1.166e+00  7.998e-02  14.581  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 37715  on 119999  degrees of freedom\nResidual deviance: 22185  on 119989  degrees of freedom\nAIC: 22207\n\nNumber of Fisher Scoring iterations: 10\n```\n:::\n\n```{.r .cell-code}\nset.seed(821)\ntrain_indices <- sample(1:nrow(combirth), 0.7 * nrow(combirth))\ntrain_data <- combirth[train_indices, ]\ntest_data <- combirth[-train_indices, ]\nglmlogistic_model_train <- glm(underage ~ Year  + meduc + m_ht_in + bmi + pwgt_r + dwgt_r + Married + GDiabetes + cig_before + cig_during, \n                               family = binomial(), \n                               data = train_data)\npredictions <- predict(glmlogistic_model_train, newdata = test_data, type = \"response\")\nmse <- mean((test_data$underage - predictions)^2)\nprint(mse)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.02787073\n```\n:::\n\n```{.r .cell-code}\npredicted_class <- ifelse(predictions > 0.5, 1, 0)\naccuracy <- mean(predicted_class == test_data$underage)\nprint(accuracy)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9590556\n```\n:::\n:::\n\n# Summary of fundings. \nlogistic_model2 has a slightly lower AIC compared to logistic_model1, suggesting a better balance between goodness of fit and model complexity.\nlogistic_model3 has a higher AIC, indicating a less favorable model fit compared to the other two.\nFirstly, Our regression model('motheragemodel') indicates a significant influence of mathernal age on birth outcomes. For every one-year increase in mathernal age, we observed a decreae in birth weight by about 4.85 grams.\n\nSecondly, our model also highlights the positive impact of mathernal education('meduc'). With each additional year of education, there's an estimated 8.92 grams increase in birth weight, and the p value is less than alpha, which shows the importance of education in maternal and child health.\n\nLastly, Smoking habits before and during pregnancy (cig_before, cig_during) shows mothers who smoked before pregnancy had babies weighing 67.20 grams more than non-smokers. In addition, for mother who smoking during pregnancy, their babies weighing 259.91 grams less. This result shows extreme negative effects of continued smoking during pregnancy.\n\n\n",
    "supporting": [
      "blog-post-7_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}